# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to=b'')),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
