# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
