# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170322_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(),
        ),
    ]
