# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20170322_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instructor_course'),
        ),
    ]
