# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20170329_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='date',
            field=models.DateField(default=datetime.date(2017, 3, 29), null=True),
        ),
    ]
