# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0009_auto_20170329_0934'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Master',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
                ('schedule_startdate', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], max_length=10)),
                ('Class_completion_status', models.CharField(choices=[('Started', 'Started'), ('Panding', 'Panding'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=10)),
                ('Extra_notes', models.CharField(max_length=255)),
                ('Dcreated', models.DateTimeField()),
                ('Instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instructor_course')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course_details')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Member',
            fields=[
                ('class_member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_details.Class_Master')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
