# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('usertype', models.CharField(choices=[('member', 'member'), ('instructor', 'instructor'), ('administrator', 'administrator')], max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('contact', models.IntegerField()),
                ('qualification', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='media/image')),
                ('resume', models.FileField(upload_to='media/resume')),
                ('joiningdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
