# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('follow_up', models.CharField(max_length=20)),
                ('extra_note', models.TextField(max_length=255)),
            ],
        ),
    ]
