# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-01 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_auto_20170401_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField()),
                ('t_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Item',
            fields=[
                ('order_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Total_Amount', models.IntegerField()),
                ('course_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course_details')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='order_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders_Item'),
        ),
    ]
